<a href="https://colab.research.google.com/github/om-srivastav/AIML-Learning-Journey/blob/main/AIML_%3E3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy 3.2

In [ ]:
a=[3,5.6,"OM",True]
type(a)

list

In [ ]:
print(a)

[3, 5.6, 'OM', True]


In [ ]:
import numpy as np
b=np.array(a)
print(b)

['3' '5.6' 'OM' 'True']


In [ ]:
a=[4,3,2,2]
b=np.array(a)
type(a)

list

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b+2

array([6, 5, 4, 4])

In [ ]:
b**2

array([16,  9,  4,  4])

In [ ]:
a=np.array([4,3,1])
b=np.array([3,4,4])
a+b

array([7, 7, 5])

In [ ]:
a*b

array([12, 12,  4])

In [ ]:
a-b

array([ 1, -1, -3])

In [ ]:
#given a list of prices, update them with gst included prices..
prices=[50,10,33,44,56]
gst_p = []
for p in prices:
  gst_p.append(p+0.18*p)
print(gst_p)

[59.0, 11.8, 38.94, 51.92, 66.08]


In [ ]:
npp=np.array(prices)
gst_np=npp*1.18

In [ ]:
print(gst_np)

[59.   11.8  38.94 51.92 66.08]


In [ ]:
np_prices=np.array(prices)
gst_np=np_prices*1.18
print(gst_np)

[59.   11.8  38.94 51.92 66.08]


In [ ]:
v=np.arange(1,10)
print(v)

[1 2 3 4 5 6 7 8 9]


In [ ]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
#gst -> p+18%p=p+0.18*p=p(1+0.18)=1.18*p

#Lec2

In [ ]:
num=(4,5,6,7)
a= np.array(num)
print(a)

[4 5 6 7]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
type(num)

tuple

In [ ]:
a=np.array([5,4,6,6.5,9])


In [ ]:
print(a)

[5.  4.  6.  6.5 9. ]


In [ ]:
names=np.array(["Om","Yoo"])
print(names)

['Om' 'Yoo']


In [ ]:
type(names)

numpy.ndarray

In [ ]:
marks=np.array([
    [70,80,90],
    [90,34,56]
  ])

In [ ]:
marks[0][1]

np.int64(80)

In [ ]:
marks[0,1]

np.int64(80)

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [ ]:
np.full(6,2)

array([2, 2, 2, 2, 2, 2])

In [ ]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
#0 to 10 all even numbers: by linspace and arange
a=np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
print(b.dtype)

int64


In [ ]:
a=np.array([True,False])
a.dtype

dtype('bool')

In [ ]:
a= np .array([10,20,30],dtype=float)
print(a)

[10. 20. 30.]


In [ ]:
a.dtype

dtype('float64')

In [ ]:
b=np.array([1.0,2.0,3.0],dtype=int)
print(b)

[1 2 3]


In [ ]:
b.dtype

dtype('int64')

In [ ]:
c=np.array([2,3,45,0,4],dtype= bool)
print(c)

[ True  True  True False  True]


In [ ]:
import numpy as np
marks=np.array([60,70,80,90,100])
bonus = marks+5
final_marks= bonus+1
print(marks)
print(bonus)
print(final_marks)

[ 60  70  80  90 100]
[ 65  75  85  95 105]
[ 66  76  86  96 106]


In [ ]:
import numpy as np
num=[10,20,30]
list_result=num*2
arr=np.array(num)
arr_res=arr*2
print(list_result)
print(arr_res)

[10, 20, 30, 10, 20, 30]
[20 40 60]


In [48]:
import numpy as np
prices= np.array([100,200,300,400,500])
discount=prices*0.10
final_price= prices-discount
print(discount)
print(final_price)

[10. 20. 30. 40. 50.]
[ 90. 180. 270. 360. 450.]


In [50]:
import numpy as np
num=np.arange(2,21,3)
print(num)
print(num[0])
print(num[-1])
print(len(num))
print(num*2)

[ 2  5  8 11 14 17 20]
2
20
7
[ 4 10 16 22 28 34 40]


In [51]:
import numpy as np
values=np.linspace(0,20,5)
print(values)
doubled=values*2
print(doubled)
print(values*10)
print(values/2)

[ 0.  5. 10. 15. 20.]
[ 0. 10. 20. 30. 40.]
[  0.  50. 100. 150. 200.]
[ 0.   2.5  5.   7.5 10. ]


In [52]:
values=np.linspace(0,20,5)
print(values)

[ 0.  5. 10. 15. 20.]


In [53]:
import numpy as np
values=np.linspace(0,20,5)
print(values)
doubled=values*2
print(doubled)
print(values*10)
print(values/2)

[ 0.  5. 10. 15. 20.]
[ 0. 10. 20. 30. 40.]
[  0.  50. 100. 150. 200.]
[ 0.   2.5  5.   7.5 10. ]


In [55]:
import numpy as np
attendance = np.zeros(5)
print(attendance)
attendance=attendance +5
print(attendance)

attendance=attendance *5
print(attendance)


[0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5.]
[25. 25. 25. 25. 25.]


In [56]:
import numpy as np
salary=np.full(5,30000)
print(salary)
increment=salary*0.10
print(increment)
new_sal=salary+increment
print(new_sal)
print(new_sal*2)

[30000 30000 30000 30000 30000]
[3000. 3000. 3000. 3000. 3000.]
[33000. 33000. 33000. 33000. 33000.]
[66000. 66000. 66000. 66000. 66000.]


In [57]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
print(arr.dtype)
res=arr*2
print(res)
print(res.dtype)

[10 20 30 40]
int64
[20 40 60 80]
int64


In [58]:
import numpy as np
marks=np.array([[70,30,50],[60,75,85]])
print(marks)
print(marks+5)
print(marks+5)
print(marks*7)

[[70 30 50]
 [60 75 85]]
[[75 35 55]
 [65 80 90]]
[[75 35 55]
 [65 80 90]]
[[490 210 350]
 [420 525 595]]


In [63]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([1,23,4,3])
add=a+b
subs=a-b
muls=a*b
print(add)
print(subs)
print(muls)

[11 43 34 43]
[ 9 -3 26 37]
[ 10 460 120 120]


In [64]:
import numpy as np
sal=np.array([30000,40000,50000,60000])
incre= sal*0.5
new_sal=sal+incre
print(sal)
print(incre)
print(new_sal)
bonus=new_sal*0.06
print(bonus)

[30000 40000 50000 60000]
[15000. 20000. 25000. 30000.]
[45000. 60000. 75000. 90000.]
[2700. 3600. 4500. 5400.]


In [65]:
new_sal+bonus

array([47700., 63600., 79500., 95400.])

In [66]:
import numpy as np
num=np.arange(2,21,2)
print(num)
res=num+1
print(res)
res=res*2
print(res)
print(len(num))

[ 2  4  6  8 10 12 14 16 18 20]
[ 3  5  7  9 11 13 15 17 19 21]
[ 6 10 14 18 22 26 30 34 38 42]
10


In [67]:
import numpy as np
a=np.arange(0,11,2)
b=np.linspace(0,10,6)
print(a)
print(b)
print(a*2)
print(b*2)
print(len(a))
print(len(b))

[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10.]
[ 0  4  8 12 16 20]
[ 0.  4.  8. 12. 16. 20.]
6
6


In [69]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1.5,2.5,3.5])
print(a.dtype)
print(b.dtype)
c=a+b
print(c)
print(c.dtype)

int64
float64
[2.5 4.5 6.5]
float64
