<a href="https://colab.research.google.com/github/om-srivastav/AIML-Learning-Journey/blob/main/AIML_%3E3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy->Numerical Python
for mathematical operations/computatiions
working with numbers in any field like ml,ds
@fundamental library

In [3]:
marks=[55,90,40,70,80]
bonus=5
new_marks=[]
for m in marks:
  new_marks.append(m+bonus)
print(new_marks)

[60, 95, 45, 75, 85]


In [5]:
import numpy as np
marks=np.array([55,90,40,70,80])
bonus=10
new_marks=marks+bonus
print(new_marks)

[ 65 100  50  80  90]


In [6]:
a=[4,56,7,8]
a[0]

4

In [7]:
a[1]

56

In [8]:
a.append(11)

In [9]:
a

[4, 56, 7, 8, 11]

In [13]:
a=[4,5,6,4]
type(a)

list

In [14]:
np_a=np.array(a)
print(np_a)

[4 5 6 4]


In [15]:
type(np_a)

numpy.ndarray

In [21]:
#given a python list:
a=[2,34,4,5]
# twice=2
b=[]

n=np.array(a)
print(n*2)

# or
for x in a:
  b.append(x*2)
print(b)

[ 4 68  8 10]
[4, 68, 8, 10]


In [22]:
type(n)

numpy.ndarray

In [23]:
n-2

array([ 0, 32,  2,  3])

In [24]:
n*0


array([0, 0, 0, 0])

In [29]:
n/7

array([0.28571429, 4.85714286, 0.57142857, 0.71428571])

In [34]:
#2d numpy array-->combinations of 1ds-->tabular format
a=[[2,34,5],[4,5,6],[55,66,7]]
b=np.array(a)
print(b)#matrix form
print(type(b))
type(b)

[[ 2 34  5]
 [ 4  5  6]
 [55 66  7]]
<class 'numpy.ndarray'>


numpy.ndarray

In [38]:
n=int(input())
a=np.zeros(n)#floating zeros
print(a)

4
[0. 0. 0. 0.]


In [41]:
a=np.zeros((4,3))#4x3 matrix->4 rows and 3 cols
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
a= np.ones(4)
print(a)

[1. 1. 1. 1.]


In [45]:
a=np.ones((4,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
a=np.arange(5)#-->0 to n-1
a

array([0, 1, 2, 3, 4])

In [48]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
a=np.arange(2,11,2)
a

array([ 2,  4,  6,  8, 10])

In [54]:
a=np.arange(1,32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [58]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#Arithmetic Ops

In [61]:
a=np.array([4,5,6])
b=np.array([4,4,6])
a


array([4, 5, 6])

In [62]:
b

array([4, 4, 6])

In [69]:
a=[4,5,6]
b=[4,4,6]
c=[]
n=len(a)
for i in range(n):
  c.append(a[i]+b[i])
print(c)
# c=[8,9,12]

[8, 9, 12]


In [71]:
an=np.array(a)
bn=np.array(b)
c=an+bn
print(c)

[ 8  9 12]


In [72]:
print(an-bn)

[0 1 0]


In [74]:
print(an*bn)

[16 20 36]


In [75]:
print(an**2)

[16 25 36]


In [76]:
print(an)

[4 5 6]
