<a href="https://colab.research.google.com/github/om-srivastav/AIML-Learning-Journey/blob/main/AIML_%3E3_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a= np.array([1,2,3])
b=np.array([1.5,2.5,3.5])
print(a.dtype)
print(b.dtype)
c=a+b
print(c)
print(c.dtype)

int64
float64
[2.5 4.5 6.5]
float64


In [3]:
import numpy as np
arr=np.array([10.5,20.7,20.9],dtype=int)
print(arr)
print(arr.dtype)
res=arr+5
print(res)
print(res*2)

[10 20 20]
int64
[15 25 25]
[30 50 50]


In [4]:
# import numpy as np
# arr=np.array(["don","dev","om"],dtype=int)#value error

In [7]:
import numpy as np
arr=np.zeros((3,4))
print(arr)
print(arr*10)
print(arr*5)
print(arr*100)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
import numpy as np
arr=np.ones((2,3))
print(arr)
res=arr*10
print(res)
res=res*5
print(res)
res=res/5
print(res)

[[1. 1. 1.]
 [1. 1. 1.]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[50. 50. 50.]
 [50. 50. 50.]]
[[10. 10. 10.]
 [10. 10. 10.]]


In [9]:
import numpy as np
arr=np.full(4,50)
print(arr)
arr=arr+20
print(arr)
print(arr*2)
print(arr)

[50 50 50 50]
[70 70 70 70]
[140 140 140 140]
[70 70 70 70]


In [10]:
import numpy as np
celcius = np.array([0,10,20,30])
f=celcius*9/5+32
print(f)

[32. 50. 68. 86.]


In [11]:
# #a student bus scored
# # 65 72 80 88 91
# create anumpy array containing these marks
# add 5 bonus marks to every subject and display original marks and updated marks

In [12]:
import numpy as np
marks = np.array([55,65,88,91,67])
bonus=5
updated_marks=marks+bonus
print(updated_marks)
print(marks)

[60 70 93 96 72]
[55 65 88 91 67]


In [13]:
# A shop has five productss with price:
# 100,22,444,556,543
# create a numpy array
# and calculate the price after applying a 10% duscount to every prd

In [15]:
import numpy as np
prices=np.array([333,455,653,345])
discount=(prices*10)/100#prices*0.1
prices_dis=prices-discount#prices*0.9
print(prices)
print(prices_dis)

[333 455 653 345]
[299.7 409.5 587.7 310.5]


In [16]:
# # a company with salaries
# 40000,400050,40344,343534
# create a numpya rray and give ebry  employemmt a 10 % slary incre

In [24]:
import numpy as np
sal=np.array([3333,55534,65,343])
incre_sal=sal+(sal*0.1)
inc=sal*1.1
print(incre_sal)
print(inc)

[ 3666.3 61087.4    71.5   377.3]
[ 3666.3 61087.4    71.5   377.3]


In [25]:
# a student marks are stored in a tuple:
# (55,66,78,44,33)
# convert the tuple into a numpy array and add 3 marks to evry value


In [26]:
import numpy as np
tup=(333,44,555,66,3)
np_tup=np.array(tup)
add=np_tup+3
add

array([336,  47, 558,  69,   6])

In [27]:
# two bramnces A and B a compnay have inventory for 5 prdt
# creat two numpy array
# calc:
# total onvemtory for each prd
# diff between a and b
# combined inventory after receiving an additional 20 units o f eberhy prd

In [29]:
A=np.array([120,234,456,544])
B=np.array([80,90,44,55])
print(A+B)
print(abs(A-B))
print(A+B+20)

[200 324 500 599]
[ 40 144 412 489]
[220 344 520 619]


In [31]:
# a store sells four prds:
# prices given
# units sold given
#  calc the revenue genrreted by each prd
#  the tore then wants to increase revenue figures by 5% for forecasting purpise

In [32]:
import numpy as np
prices=np.array([250,400,750])
units=np.array([12,33,44])
revenue=prices+units
forecast=revenue*1.05
print(revenue)
print(forecast)

[262 433 794]
[275.1  454.65 833.7 ]


In [33]:
import numpy as np
marks=np.array([70,50,40,30])
print(marks)

[70 50 40 30]


In [34]:
len(marks)

4

In [36]:
arr2=np.array([    [80,20,30],
    [33,44,55],
    [54,43,32]]
)
print(arr2)

[[80 20 30]
 [33 44 55]
 [54 43 32]]


In [38]:
# how many dimension does the array have
marks.ndim

1

In [39]:
arr2.ndim

2

In [41]:
a=np.array([[[1,2],
             [3,4]],
            [[5,6],
             [7,6]]])
a.ndim

3

# concept of shape

In [43]:
a.shape

(2, 2, 2)

In [44]:
arr.shape

(4,)

In [45]:
arr2.shape

(3, 3)

In [46]:
arr2.size

9

In [47]:
len(arr2)

3

In [49]:
arr=np.array([10.4,44.4,44.5])
arr_int=arr.astype(int)#will convert in integer numpy array of arr

In [50]:
arr

array([10.4, 44.4, 44.5])

In [53]:
arr_int

array([10, 44, 44])

In [52]:
# in dtype--->original array got affected
# in astype--->original array not affected#do changes in copy

In [54]:
data = np.array([
    [10,203,30,40],
    [50,40,30,20],
    [40,303,222,22]
])
print(len(data))
print(data.size)
print(data.shape)
print(data.ndim)

3
12
(3, 4)
2


In [55]:
# # college wants to itialise a mrks table for  5 student and 4 subs
# initialy evry student  marks are set  to 0
# reate this usig npthe create another 5x 4 array containing adefault value of 50


In [56]:
std_marks=np.zeros((5,4))
print(std_marks)
print(std_marks+50)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]


In [57]:
updated = np.full((5,4),50)
print(updated)

[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]


In [60]:
score=np.array([45,56,67,88,65])
score=score+3
fscore=score*0.1
final=fscore+score
print(final)


[ 52.8  64.9  77.  100.1  74.8]
